"""Complete remodeling

Revision ID: 7541aaf04684
Revises: d7515a081954
Create Date: 2023-06-18 17:39:13.620462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7541aaf04684'
down_revision = 'd7515a081954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
    
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_column('last_seen')
        batch_op.drop_column('username')
    
    # ### end Alembic commands ###

